In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print("list:",arr)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print("array:",arr)
print("type of the array:",type(arr))

In [ ]:
import numpy as np
tup=(1,2,3,4)
print("tuple is:\n",tup)
print(type(tup))
print("convert tuple to list:")
arr=np.asarray(tup)
print(arr)
print(type(arr))

In [ ]:
import numpy as np
a=np.array([1,2,3,4])
print("1D array:")
print(a)

In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print("2D array:")
print(a)

In [ ]:
import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8]])
print("dimension is:\n",a.shape)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=arr.reshape(3,2)
print("Reshaped array is:\n",newarr)

In [ ]:
import numpy as np
a=np.zeros([2,2])
print("zero matrix:\n",a)

In [ ]:
import numpy as np
a=np.zeros(2)
print("zero matrix:\n",a)

In [ ]:
import numpy as np
a=np.ones([4,4])
print("ones matrix:\n",a)

In [ ]:
import numpy as np
a=np.ones([4,4],dtype=int)
print("ones matrix in integer:\n",a)

In [ ]:
import numpy as np
a=np.eye(3,3,dtype=int)
print("identity matrix:\n",a)


In [ ]:
import numpy as np
a=np.eye(3,3)
print("identity matrix:\n",a)

In [ ]:
import numpy as np
a=np.arange(0,11)
print("Range is:\n",a)

In [ ]:
import numpy as np
a=int(input("enter a start value:"))
b=int(input("enter a end value:"))
a=np.arange(a,b)
print("identity matrix:\n",a)

In [ ]:
import numpy as np
a=np.array([2,4,6,8])
b=np.array([3,5,9,11])
c=np.add(a,b)
d=(a-b)
e=(b-a)
f=(a**2)
print("addition of 2 1D array:\n",c)
print("a-b of 2 1D array:\n",d)
print("b-a of 2 1D array:\n",e)
print("a**2 of 2 1D array:\n",f)

In [ ]:
import numpy as np
a=np.linspace(2,3,num=7)
print(a)

In [ ]:
import numpy as np
a=np.linspace(2,3,num=7,dtype=int)
print(a)


In [ ]:
import numpy as np
a=np.linspace(2,3,num=7,endpoint=False,dtype=int)
print(a)

In [ ]:
import numpy as np
a=np.linspace(2,3,num=7,endpoint=True,dtype=int)
print(a)

In [ ]:
import numpy as np
a=np.linspace(2,3,num=7,retstep=True,dtype=int)
print(a)

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
print("array is:\n",arr)
arr.resize(3,3)
print("Resized array is:\n",arr)

In [ ]:
import numpy as np
x=np.rand(5)
print (x)

In [ ]:
import numpy as np
a=np.array([[1,4,1],[2,3,4],[3,2,1]])
U,D,VT=np.linalg.svd(a)
a_remake=(U @np.diag(D)@VT)
print(a_remake)

[[1. 4. 1.]
 [2. 3. 4.]
 [3. 2. 1.]]


In [ ]:
import numpy as np
a=np.array([[1,4,1],[2,3,4],[3,2,1]])
U,D,VT=np.linalg.svd(a)
print(a)

[[1 4 1]
 [2 3 4]
 [3 2 1]]


In [ ]:
a=[[1,2],
   [3,5],
   [5,6]]
Transpose=[[0,0,0],
           [0,0,0]]
for i in range(len(a)):
    for j in range(len(a[0])):
          Transpose[j][i]=a[i][j]
for T in Transpose:
  print(T)
                        

[1, 3, 5]
[2, 5, 6]
